package uk.ac.ed.inf.util;

public enum SuccessStatus {
    CONNECTING_TO_REST_SERVER,
    HTTP_STATUS_CODE,
    RUNNING_PIZZADRONZ_CONTROLLER,
    FINISHED,
    VALIDATED_ORDERS,
    GENERATING_FLIGHT_PATHS,
    SUCCESSFULLY_GENERATED_FLIGHT_PATHS,
    SUCCESSFULLY_CREATED_DELIVERIES_JSON_FILE,
    SUCCESSFULLY_CREATED_FLIGHT_PATHS_JSON_FILE,
    SUCCESSFULLY_CREATED_DRONE_PATHS_GEOJSON_FILE, SUCCESSFULLY_FETCHED_DATA, SUCCESSFULLY_CREATED_ALL_FILES;
}
